language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-flux' ]; then cd .. && eval "mv $currentfolder generator-flux" && cd generator-flux; fi

